### ISSUE TITLE
truegaze can't find config file

### ISSUE THREAD

**Issue by krviolet** [nightwatchcybersecurity/truegaze#1]
Identified as an Android application via a manifest located at: AndroidManifest.xml

Scanning using the "AdobeMobileSdk" plugin
-- Cannot find the "ADBMobileConfig.json" file, skipping

**Comment by nightwatchcyber** [comment]
This is not an error - it indicates that this application isn't integrated with Adobe and the test will be skipped. I changed the message to clarify this.
