### ISSUE TITLE
Cannot detect iOS App

### ISSUE THREAD

**Issue by sushi2k** [nightwatchcybersecurity/truegaze#3]
Hi, 

thanks for creating the tool. I just installed and tested it, but it only works sometimes with some of the well known vulnerable apps:

Working with DamnVulnerableiOSApp

```bash
$truegaze scan DamnVulnerableiOSApp.ipa

Processing file: DamnVulnerableiOSApp.ipa
Identified as an iOS application via a manifest located at: Payload/DamnVulnerableIOSApp.app/Info.plist

Scanning using the "AdobeMobileSdk" plugin
-- No Adobe integration in this application (no "ADBMobileConfig.json" file); skipping test

Scanning using the "FirebasePlugin" plugin
-- OS is not supported by this plugin, skipping

Scanning using the "WeakKeyPlugin" plugin
-- OS is not supported by this plugin, skipping
Done!
```

Not working with iGoat and DVIAv2:

```bash
$ truegaze scan iGoat-Swift_v1.0.ipa

Processing file: iGoat-Swift_v1.0.ipa
ERROR: Unable to identify the file as an Android or iOS application

$ truegaze scan DVIA-v2-swift.ipa

Processing file: DVIA-v2-swift.ipa
ERROR: Unable to identify the file as an Android or iOS application
```

**Comment by nightwatchcyber** [comment]
As seen at the link below, there are only a few specific tests included here for now:
https://github.com/nightwatchcybersecurity/truegaze#sample-output

**Comment by sushi2k** [comment]
Thanks for the quick answer and noted on the limited test cases at the moment. But I was referring to the errors with iGoat and DVIAv2, as it cannot identify if it's an iOS or Android app:

```bash
$ truegaze scan iGoat-Swift_v1.0.ipa

Processing file: iGoat-Swift_v1.0.ipa
ERROR: Unable to identify the file as an Android or iOS application

$ truegaze scan DVIA-v2-swift.ipa

Processing file: DVIA-v2-swift.ipa
ERROR: Unable to identify the file as an Android or iOS application
```

**Comment by nightwatchcyber** [comment]
Ah makes sense, something is wrong with the detection mechanism. I will take a look.

Thanks for letting me know

**Comment by nightwatchcyber** [comment]
I fixed this in source code, will go out in the 0.1.5 release - probably in a few weeks

Thanks for the report!
