### ISSUE TITLE
Test All Skip!

### ISSUE THREAD

**Issue by xjh093** [nightwatchcybersecurity/truegaze#9]
Processing file: xxx.ipa
Identified as an iOS application via a manifest located at: Payload/xxx.app/Info.plist

Scanning using the "AdobeMobileSdk" plugin
-- No Adobe integration in this application (no "ADBMobileConfig.json" file); skipping test

Scanning using the "FirebasePlugin" plugin
-- OS is not supported by this plugin, skipping

Scanning using the "WeakKeyPlugin" plugin
-- OS is not supported by this plugin, skipping
Done!

**Comment by nightwatchcyber** [comment]
Not all plugins are applicable across all platforms, in this case the Firebase and WeakKey plugins only work on Android devices. The Adobe plugin works across all platforms.

**Comment by xjh093** [comment]
ok~
